"""Set metadata.streams on already-imported CBSE and ISC Class XI-XII nodes.

ingest_ncert.py and ingest_isc.py set it at import time from subject_streams.py;
this brings existing rows up to date without re-importing (which would churn
node ids and embeddings). Idempotent: rows that already hold the right list
are left alone.

Usage (from backend/rag-pipeline/):
    python ingest/backfill_subject_streams.py --dry-run
    python ingest/backfill_subject_streams.py --emit-sql out.sql
        then: npx supabase db query --linked -f out.sql   (from backend/)
    python ingest/backfill_subject_streams.py
        row-by-row through the API; slow (~4,500 rows), use --emit-sql instead
"""

from __future__ import annotations

import argparse
import json
import sys
import time
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
sys.path.insert(0, str(Path(__file__).resolve().parent))

from db.supabase_client import get_client  # noqa: E402
from subject_streams import STREAM_FIRST_GRADE, SUBJECT_STREAMS, subject_streams  # noqa: E402

CURRICULA = ["ncert-cbse", "isc-cisce"]


def sql_literal(text: str) -> str:
    return "'" + text.replace("'", "''") + "'"


def emit_sql(path: Path) -> None:
    """One UPDATE per subject, skipping rows that already match."""
    systems = ", ".join(sql_literal(c) for c in CURRICULA)
    lines = [
        "-- Generated by backfill_subject_streams.py from subject_streams.py.",
        "BEGIN;",
    ]
    for subject, streams in SUBJECT_STREAMS.items():
        value = sql_literal(json.dumps(streams))
        lines.append(
            f"UPDATE public.curriculum_nodes SET metadata = jsonb_set(metadata, '{{streams}}', {value}::jsonb)\n"
            f"WHERE curriculum_system IN ({systems}) AND grade_level_min >= {STREAM_FIRST_GRADE}\n"
            f"  AND metadata->>'subject' = {sql_literal(subject)}\n"
            f"  AND metadata->'streams' IS DISTINCT FROM {value}::jsonb;"
        )
    # Subjects outside the map (Physical Education) belong to no stream.
    known = ", ".join(sql_literal(s) for s in SUBJECT_STREAMS)
    lines.append(
        "UPDATE public.curriculum_nodes SET metadata = jsonb_set(metadata, '{streams}', '[]'::jsonb)\n"
        f"WHERE curriculum_system IN ({systems}) AND grade_level_min >= {STREAM_FIRST_GRADE}\n"
        f"  AND metadata->>'subject' NOT IN ({known})\n"
        "  AND metadata->'streams' IS DISTINCT FROM '[]'::jsonb;"
    )
    lines.append("COMMIT;")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {path}")


def fetch_rows(client, curriculum: str) -> list[dict]:
    rows, offset = [], 0
    while True:
        page = (client.table("curriculum_nodes")
                .select("id, grade_level_min, metadata->>subject, metadata->streams")
                .eq("curriculum_system", curriculum).gte("grade_level_min", STREAM_FIRST_GRADE)
                .range(offset, offset + 999).execute().data or [])
        rows += page
        if len(page) < 1000:
            return rows
        offset += len(page)


def main() -> int:
    parser = argparse.ArgumentParser(description="Backfill Class XI-XII stream metadata")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--emit-sql", type=Path, metavar="PATH")
    args = parser.parse_args()

    if args.emit_sql:
        emit_sql(args.emit_sql)
        return 0

    client = get_client()
    todo = []
    for curriculum in CURRICULA:
        rows = fetch_rows(client, curriculum)
        stale = [(r["id"], r["subject"], subject_streams(r["subject"] or "", r["grade_level_min"]))
                 for r in rows
                 if r["streams"] != subject_streams(r["subject"] or "", r["grade_level_min"])]
        print(f"{curriculum}: {len(rows)} Class XI-XII nodes, {len(stale)} need updating")
        todo += stale

    if args.dry_run:
        for (subject, streams), n in sorted(Counter((s, tuple(w)) for _, s, w in todo).items()):
            print(f"   {subject:<20} {list(streams)}  x{n}")
        return 0

    failed = 0
    for i, (node_id, _, streams) in enumerate(todo, 1):
        # Read-modify-write per row: PostgREST has no jsonb_set, and metadata
        # holds other keys that must survive.
        for attempt in range(3):
            try:
                meta = (client.table("curriculum_nodes").select("metadata")
                        .eq("id", node_id).single().execute().data["metadata"]) or {}
                meta["streams"] = streams
                client.table("curriculum_nodes").update({"metadata": meta}).eq("id", node_id).execute()
                break
            except Exception as exc:  # noqa: BLE001 - retry transient errors, report the rest
                if attempt == 2:
                    failed += 1
                    print(f"   FAILED {node_id}: {str(exc)[:80]}")
                time.sleep(1 + attempt)
        if i % 250 == 0:
            print(f"   {i}/{len(todo)}")
    print(f"done: {len(todo) - failed} updated, {failed} failed")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
