-- Canonical subject mapping for US state standards.
--
-- US curriculum data stores each state's own label for a standards document in
-- curriculum_nodes.metadata->>'subject'. Across the 51 jurisdictions that is
-- 1,053 distinct strings for a handful of real subjects: labels carry vintage
-- ranges ("Science (1998-2013)" next to "Science (2013-)"), state branding
-- ("Mathematics (B.E.S.T.)"), and a large share of non-academic documents
-- (career/technical clusters, early-childhood guidelines, teacher evaluation,
-- library media, assessment blueprints, alternate standards).
--
-- This table resolves every raw label to a canonical subject and domain, or
-- marks it excluded with a reason. It is the single source of truth for both
-- the assessment form's US subject list and the gap engine's per-subject
-- source pools. Rows are generated by backend/rag-pipeline/ingest/
-- us_subject_mapping.py and seeded by the companion migration
-- 20261005000001_seed_subject_mappings.sql.
--
-- domain values must match SubjectDomain in supabase/functions/_shared/
-- curriculumGaps.ts.

CREATE TABLE IF NOT EXISTS public.subject_mappings (
  raw_subject        TEXT PRIMARY KEY,
  canonical_subject  TEXT,
  domain             TEXT,
  is_core            BOOLEAN NOT NULL DEFAULT FALSE,
  -- End year of the label's closed year range ("(1998-2013)" -> 2013); NULL
  -- for open-ended or undated labels. Currency is decided at query time
  -- against today's date, so a "(2021-2026)" label rolls over to superseded
  -- in 2027 without regenerating anything.
  vintage_end        INT,
  excluded_reason    TEXT,
  created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT subject_mappings_mapped_or_excluded CHECK (
    (canonical_subject IS NOT NULL AND domain IS NOT NULL AND excluded_reason IS NULL)
    OR (canonical_subject IS NULL AND domain IS NULL AND excluded_reason IS NOT NULL)
  )
);

CREATE INDEX IF NOT EXISTS idx_subject_mappings_canonical
  ON public.subject_mappings (canonical_subject)
  WHERE canonical_subject IS NOT NULL;

-- Reference data with no personal information. Enabled explicitly, with an
-- explicit read policy, because this project has had tables reach production
-- with RLS on and zero policies (shared_reports, profiles, student_profiles).
-- Writes have no policy, so only the service role can change mappings.
ALTER TABLE public.subject_mappings ENABLE ROW LEVEL SECURITY;

-- Table privileges are granted explicitly rather than left to Supabase's
-- default privileges: RLS policies alone don't give a role access to a table
-- it holds no privilege on.
GRANT SELECT ON public.subject_mappings TO anon, authenticated;
GRANT ALL ON public.subject_mappings TO service_role;

DROP POLICY IF EXISTS "Subject mappings are readable" ON public.subject_mappings;
CREATE POLICY "Subject mappings are readable"
  ON public.subject_mappings
  FOR SELECT
  TO anon, authenticated
  USING (true);


-- Canonical subjects a curriculum teaches across a grade range.
--
-- p_grade_min / p_grade_max select nodes whose grade range overlaps the
-- window. The assessment form asks for one grade (min = max = that grade);
-- the gap engine asks for the cumulative window a student has been taught,
-- [1, current grade], because a label covering only earlier grades still holds
-- content the student learned. Grade-0 nodes apply to every grade
-- (see 20260828000000). Both NULL returns every grade.
--
-- raw_subjects lists the exact labels behind each canonical subject. Only
-- current vintages are returned; when a subject has none (South Carolina's core
-- subjects are all closed-range), only its most recent superseded vintage is,
-- so a 2015-2023 standard isn't pooled with the 2008 one it replaced.
-- The gap engine passes them as source_subjects to find_curriculum_gaps_rag,
-- replacing broad ILIKE patterns that pooled every vintage together.
CREATE OR REPLACE FUNCTION public.get_canonical_subjects(
  p_curriculum_system TEXT,
  p_grade_min         INT     DEFAULT NULL,
  p_grade_max         INT     DEFAULT NULL,
  p_core_only         BOOLEAN DEFAULT FALSE
)
RETURNS TABLE(
  canonical_subject TEXT,
  domain            TEXT,
  is_core           BOOLEAN,
  node_count        BIGINT,
  raw_subjects      TEXT[]
)
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path = public
AS $$
  WITH bounds AS (
    SELECT
      COALESCE(p_grade_min, p_grade_max) AS gmin,
      COALESCE(p_grade_max, p_grade_min) AS gmax
  ),
  scoped AS (
    SELECT cn.metadata->>'subject' AS raw_subject, COUNT(*) AS n
    FROM public.curriculum_nodes cn, bounds b
    WHERE cn.curriculum_system = p_curriculum_system
      AND cn.metadata->>'subject' IS NOT NULL
      AND (
        b.gmin IS NULL
        OR (cn.grade_level_min = 0 AND cn.grade_level_max = 0)
        OR (cn.grade_level_min <= b.gmax AND cn.grade_level_max >= b.gmin)
      )
    GROUP BY cn.metadata->>'subject'
  ),
  mapped AS (
    SELECT
      sm.canonical_subject, sm.domain, sm.is_core, sm.vintage_end, s.raw_subject, s.n,
      (sm.vintage_end IS NULL OR sm.vintage_end >= EXTRACT(YEAR FROM now())::INT) AS is_current
    FROM scoped s
    JOIN public.subject_mappings sm ON sm.raw_subject = s.raw_subject
    WHERE sm.canonical_subject IS NOT NULL
      AND (NOT p_core_only OR sm.is_core)
  ),
  currency AS (
    SELECT
      m.canonical_subject,
      bool_or(m.is_current)                          AS any_current,
      max(m.vintage_end) FILTER (WHERE NOT m.is_current) AS latest_superseded
    FROM mapped m
    GROUP BY m.canonical_subject
  )
  SELECT
    m.canonical_subject,
    m.domain,
    m.is_core,
    SUM(m.n)::BIGINT AS node_count,
    array_agg(m.raw_subject ORDER BY m.raw_subject) AS raw_subjects
  FROM mapped m
  JOIN currency c ON c.canonical_subject = m.canonical_subject
  WHERE (c.any_current AND m.is_current)
     OR (NOT c.any_current AND m.vintage_end = c.latest_superseded)
  GROUP BY m.canonical_subject, m.domain, m.is_core
  ORDER BY m.is_core DESC, m.canonical_subject;
$$;

-- anon included deliberately: the assessment form runs before sign-in.
GRANT EXECUTE ON FUNCTION public.get_canonical_subjects(TEXT, INT, INT, BOOLEAN)
  TO anon, authenticated, service_role;

COMMENT ON FUNCTION public.get_canonical_subjects(TEXT, INT, INT, BOOLEAN) IS
  'Canonical subjects (with their raw labels) a curriculum teaches across a grade window. Drives the US subject list in the assessment form and the per-subject source pools in the gap engine.';
